[2017-11-02 11:02:10,646|PLTEConnector.py:28][DEBUG] > PLTEConnector Init
[2017-11-02 11:02:10,646|PLTEManager.py:22][DEBUG] > PLTE Manager Init
[2017-11-02 11:02:10,647|Connector.py:25][DEBUG] > Connector Init
[2017-11-02 11:02:10,647|PLTEConnector.py:35][ERROR] > msgQueue Connection Failed.. PLTE QUEUE_ID[12345]
[2017-11-02 11:53:22,620|PLTEConnector.py:28][DEBUG] > PLTEConnector Init
[2017-11-02 11:53:22,620|PLTEManager.py:22][DEBUG] > PLTE Manager Init
[2017-11-02 11:53:22,620|Connector.py:25][DEBUG] > Connector Init
[2017-11-02 11:55:53,309|PLTEConnector.py:28][DEBUG] > PLTEConnector Init
[2017-11-02 11:55:53,310|PLTEManager.py:22][DEBUG] > PLTE Manager Init
[2017-11-02 11:55:53,310|Connector.py:25][DEBUG] > Connector Init
[2017-11-02 11:56:57,405|PLTEConnector.py:28][DEBUG] > PLTEConnector Init
[2017-11-02 11:56:57,406|PLTEManager.py:22][DEBUG] > PLTE Manager Init
[2017-11-02 11:56:57,406|Connector.py:25][DEBUG] > Connector Init
[2017-11-02 12:04:46,171|ResReceiver.py:48][ERROR] > msgQueue Connection Failed.. RESTIF_S QUEUE_ID[54322] Permission denied
[2017-11-02 12:04:46,171|PLTEConnector.py:28][DEBUG] > PLTEConnector Init
[2017-11-02 12:04:46,172|PLTEManager.py:22][DEBUG] > PLTE Manager Init
[2017-11-02 12:04:46,172|Connector.py:25][DEBUG] > Connector Init
[2017-11-02 12:07:18,623|PLTEConnector.py:28][DEBUG] > PLTEConnector Init
[2017-11-02 12:07:18,624|PLTEManager.py:22][DEBUG] > PLTE Manager Init
[2017-11-02 12:07:18,624|Connector.py:25][DEBUG] > Connector Init
[2017-11-02 12:07:53,957|PLTEConnector.py:28][DEBUG] > PLTEConnector Init
[2017-11-02 12:07:53,957|PLTEManager.py:22][DEBUG] > PLTE Manager Init
[2017-11-02 12:07:53,957|Connector.py:25][DEBUG] > Connector Init
[2017-11-02 12:11:15,251|PLTEConnector.py:28][DEBUG] > PLTEConnector Init
[2017-11-02 12:11:15,251|PLTEManager.py:22][DEBUG] > PLTE Manager Init
[2017-11-02 12:11:15,251|Connector.py:25][DEBUG] > Connector Init
[2017-11-02 12:14:47,389|PLTEConnector.py:28][DEBUG] > PLTEConnector Init
[2017-11-02 12:14:47,389|PLTEManager.py:22][DEBUG] > PLTE Manager Init
[2017-11-02 12:14:47,389|Connector.py:25][DEBUG] > Connector Init
[2017-11-02 12:15:27,221|PLTEConnector.py:28][DEBUG] > PLTEConnector Init
[2017-11-02 12:15:27,221|PLTEManager.py:22][DEBUG] > PLTE Manager Init
[2017-11-02 12:15:27,221|Connector.py:25][DEBUG] > Connector Init
[2017-11-02 12:17:07,910|PLTEConnector.py:28][DEBUG] > PLTEConnector Init
[2017-11-02 12:17:07,910|PLTEManager.py:22][DEBUG] > PLTE Manager Init
[2017-11-02 12:17:07,910|Connector.py:25][DEBUG] > Connector Init
[2017-11-02 12:24:38,335|ReqReceiver.py:34][ERROR] > ReqReceiver Init
[2017-11-02 12:24:38,336|ResReceiver.py:33][INFO] > ResReceiver Init
[2017-11-02 12:24:38,336|PLTEConnector.py:28][DEBUG] > PLTEConnector Init
[2017-11-02 12:24:38,336|PLTEManager.py:22][DEBUG] > PLTE Manager Init
[2017-11-02 12:24:38,336|Connector.py:25][DEBUG] > Connector Init
[2017-11-02 12:27:49,166|ReqReceiver.py:34][ERROR] > ReqReceiver Init
[2017-11-02 12:27:49,168|ResReceiver.py:33][INFO] > ResReceiver Init
[2017-11-02 12:27:49,168|PLTEConnector.py:28][DEBUG] > PLTEConnector Init
[2017-11-02 12:27:49,168|PLTEManager.py:22][DEBUG] > PLTE Manager Init
[2017-11-02 12:27:49,168|Connector.py:25][DEBUG] > Connector Init
[2017-11-02 12:30:29,010|ReqReceiver.py:34][ERROR] > ReqReceiver Init
[2017-11-02 12:30:29,012|ResReceiver.py:33][INFO] > ResReceiver Init
[2017-11-02 12:30:29,013|PLTEConnector.py:28][DEBUG] > PLTEConnector Init
[2017-11-02 12:30:29,013|PLTEManager.py:22][DEBUG] > PLTE Manager Init
[2017-11-02 12:30:29,013|Connector.py:25][DEBUG] > Connector Init
[2017-11-02 12:31:48,896|ReqReceiver.py:34][ERROR] > ReqReceiver Init
[2017-11-02 12:31:48,897|ResReceiver.py:33][INFO] > ResReceiver Init
[2017-11-02 12:31:48,898|PLTEConnector.py:28][DEBUG] > PLTEConnector Init
[2017-11-02 12:31:48,898|PLTEManager.py:22][DEBUG] > PLTE Manager Init
[2017-11-02 12:31:48,898|Connector.py:25][DEBUG] > Connector Init
[2017-11-02 12:34:31,245|ReqReceiver.py:34][ERROR] > ReqReceiver Init
[2017-11-02 12:34:31,245|ResReceiver.py:33][INFO] > ResReceiver Init
[2017-11-02 12:34:31,246|PLTEConnector.py:28][DEBUG] > PLTEConnector Init
[2017-11-02 12:34:31,246|PLTEManager.py:22][DEBUG] > PLTE Manager Init
[2017-11-02 12:34:31,246|Connector.py:25][DEBUG] > Connector Init
[2017-11-02 12:34:31,246|PLTEConnector.py:35][ERROR] > msgQueue Connection Failed.. PLTE QUEUE_ID[12345]
[2017-11-02 12:36:35,508|ReqReceiver.py:34][ERROR] > ReqReceiver Init
[2017-11-02 12:36:35,510|ResReceiver.py:33][INFO] > ResReceiver Init
[2017-11-02 12:36:35,511|PLTEConnector.py:28][DEBUG] > PLTEConnector Init
[2017-11-02 12:36:35,511|PLTEManager.py:22][DEBUG] > PLTE Manager Init
[2017-11-02 12:36:35,511|Connector.py:25][DEBUG] > Connector Init
[2017-11-02 12:36:35,511|PLTEConnector.py:35][ERROR] > msgQueue Connection Failed.. PLTE QUEUE_ID[12345]
[2017-11-02 12:36:47,178|ReqReceiver.py:34][ERROR] > ReqReceiver Init
[2017-11-02 12:36:47,179|ResReceiver.py:33][INFO] > ResReceiver Init
[2017-11-02 12:36:47,179|PLTEConnector.py:28][DEBUG] > PLTEConnector Init
[2017-11-02 12:36:47,179|PLTEManager.py:22][DEBUG] > PLTE Manager Init
[2017-11-02 12:36:47,179|Connector.py:25][DEBUG] > Connector Init
[2017-11-02 12:46:06,373|ReqReceiver.py:34][ERROR] > ReqReceiver Init
[2017-11-02 12:46:06,375|ResReceiver.py:33][INFO] > ResReceiver Init
[2017-11-02 12:46:06,376|PLTEConnector.py:28][DEBUG] > PLTEConnector Init
[2017-11-02 12:46:06,376|PLTEManager.py:22][DEBUG] > PLTE Manager Init
[2017-11-02 12:46:06,376|Connector.py:25][DEBUG] > Connector Init
[2017-11-02 12:46:12,953|NsdManageService.py:30][INFO] > ===============================================
[2017-11-02 12:46:12,953|NsdManageService.py:31][INFO] > [WEB] -> RESTIF
[2017-11-02 12:46:12,953|NsdManageService.py:32][INFO] > ===============================================
[2017-11-02 12:46:12,958|NsdManageService.py:33][INFO] > REQUEST URL : http://175.213.170.13:8500/ns_descriptors
[2017-11-02 12:46:12,958|NsdManageService.py:34][INFO] > BODY : {u'age': 123, u'name': u'hoho'}
[2017-11-02 12:46:12,958|NsdManageService.py:35][INFO] > ===============================================
[2017-11-02 12:46:12,961|PLTEConnector.py:68][INFO] > ===============================================
[2017-11-02 12:46:12,961|PLTEConnector.py:69][INFO] > RESTIF -> PLTEIB
[2017-11-02 12:46:12,961|PLTEConnector.py:70][INFO] > ===============================================
[2017-11-02 12:46:12,962|PLTEConnector.py:71][INFO] > API_NAME : nsd-on-boarding
[2017-11-02 12:46:12,962|PLTEConnector.py:72][INFO] > PID   : 1
[2017-11-02 12:46:12,962|PLTEConnector.py:73][INFO] > BODY   : temp
[2017-11-02 12:46:12,962|PLTEConnector.py:74][INFO] > ===============================================
[2017-11-02 12:49:13,430|ReqReceiver.py:34][ERROR] > ReqReceiver Init
[2017-11-02 12:49:13,431|ResReceiver.py:33][INFO] > ResReceiver Init
[2017-11-02 12:49:13,431|PLTEConnector.py:28][DEBUG] > PLTEConnector Init
[2017-11-02 12:49:13,431|PLTEManager.py:22][DEBUG] > PLTE Manager Init
[2017-11-02 12:49:13,431|Connector.py:25][DEBUG] > Connector Init
[2017-11-02 12:49:18,781|NsdManageService.py:30][INFO] > ===============================================
[2017-11-02 12:49:18,781|NsdManageService.py:31][INFO] > [WEB] -> RESTIF
[2017-11-02 12:49:18,781|NsdManageService.py:32][INFO] > ===============================================
[2017-11-02 12:49:18,786|NsdManageService.py:33][INFO] > REQUEST URL : http://175.213.170.13:8500/ns_descriptors
[2017-11-02 12:49:18,787|NsdManageService.py:34][INFO] > BODY : {u'age': 123, u'name': u'hoho'}
[2017-11-02 12:49:18,787|NsdManageService.py:35][INFO] > ===============================================
[2017-11-02 12:49:18,787|PLTEConnector.py:68][INFO] > ===============================================
[2017-11-02 12:49:18,787|PLTEConnector.py:69][INFO] > RESTIF -> PLTEIB
[2017-11-02 12:49:18,787|PLTEConnector.py:70][INFO] > ===============================================
[2017-11-02 12:49:18,787|PLTEConnector.py:71][INFO] > API_NAME : nsd-on-boarding
[2017-11-02 12:49:18,788|PLTEConnector.py:72][INFO] > PID   : 1
[2017-11-02 12:49:18,788|PLTEConnector.py:73][INFO] > BODY   : temp
[2017-11-02 12:49:18,788|PLTEConnector.py:74][INFO] > ===============================================
[2017-11-02 13:47:42,313|ReqReceiver.py:34][ERROR] > ReqReceiver Init
[2017-11-02 13:47:42,315|ResReceiver.py:33][INFO] > ResReceiver Init
[2017-11-02 13:47:42,315|PLTEConnector.py:28][DEBUG] > PLTEConnector Init
[2017-11-02 13:47:42,315|PLTEManager.py:22][DEBUG] > PLTE Manager Init
[2017-11-02 13:47:42,316|Connector.py:25][DEBUG] > Connector Init
[2017-11-02 13:47:45,017|NsdManageService.py:30][INFO] > ===============================================
[2017-11-02 13:47:45,017|NsdManageService.py:31][INFO] > [WEB] -> RESTIF
[2017-11-02 13:47:45,017|NsdManageService.py:32][INFO] > ===============================================
[2017-11-02 13:47:45,022|NsdManageService.py:33][INFO] > REQUEST URL : http://175.213.170.13:8500/ns_descriptors
[2017-11-02 13:47:45,022|NsdManageService.py:34][INFO] > BODY : {u'age': 123, u'name': u'hoho'}
[2017-11-02 13:47:45,022|NsdManageService.py:35][INFO] > ===============================================
[2017-11-02 13:47:45,024|PLTEConnector.py:68][INFO] > ===============================================
[2017-11-02 13:47:45,024|PLTEConnector.py:69][INFO] > RESTIF -> PLTEIB
[2017-11-02 13:47:45,024|PLTEConnector.py:70][INFO] > ===============================================
[2017-11-02 13:47:45,025|PLTEConnector.py:71][INFO] > API_NAME : nsd-on-boarding
[2017-11-02 13:47:45,025|PLTEConnector.py:72][INFO] > PID   : 1
[2017-11-02 13:47:45,025|PLTEConnector.py:73][INFO] > BODY   : temp
[2017-11-02 13:47:45,025|PLTEConnector.py:74][INFO] > ===============================================
[2017-11-02 14:04:16,550|ReqReceiver.py:34][ERROR] > ReqReceiver Init
[2017-11-02 14:04:16,551|ResReceiver.py:33][INFO] > ResReceiver Init
[2017-11-02 14:04:16,551|PLTEConnector.py:28][DEBUG] > PLTEConnector Init
[2017-11-02 14:04:16,551|PLTEManager.py:22][DEBUG] > PLTE Manager Init
[2017-11-02 14:04:16,551|Connector.py:25][DEBUG] > Connector Init
[2017-11-02 14:04:21,102|NsdManageService.py:30][INFO] > ===============================================
[2017-11-02 14:04:21,102|NsdManageService.py:31][INFO] > [WEB] -> RESTIF
[2017-11-02 14:04:21,102|NsdManageService.py:32][INFO] > ===============================================
[2017-11-02 14:04:21,107|NsdManageService.py:33][INFO] > REQUEST URL : http://175.213.170.13:8500/ns_descriptors
[2017-11-02 14:04:21,107|NsdManageService.py:34][INFO] > BODY : {u'age': 123, u'name': u'hoho'}
[2017-11-02 14:04:21,108|NsdManageService.py:35][INFO] > ===============================================
[2017-11-02 14:04:21,110|PLTEConnector.py:68][INFO] > ===============================================
[2017-11-02 14:04:21,110|PLTEConnector.py:69][INFO] > RESTIF -> PLTEIB
[2017-11-02 14:04:21,110|PLTEConnector.py:70][INFO] > ===============================================
[2017-11-02 14:04:21,110|PLTEConnector.py:71][INFO] > API_NAME : nsd-on-boarding
[2017-11-02 14:04:21,110|PLTEConnector.py:72][INFO] > PID   : 1
[2017-11-02 14:04:21,110|PLTEConnector.py:73][INFO] > BODY   : temp
[2017-11-02 14:04:21,110|PLTEConnector.py:74][INFO] > ===============================================
[2017-11-02 14:05:21,099|ReqReceiver.py:34][ERROR] > ReqReceiver Init
[2017-11-02 14:05:21,100|ResReceiver.py:33][INFO] > ResReceiver Init
[2017-11-02 14:05:21,100|PLTEConnector.py:28][DEBUG] > PLTEConnector Init
[2017-11-02 14:05:21,100|PLTEManager.py:22][DEBUG] > PLTE Manager Init
[2017-11-02 14:05:21,100|Connector.py:25][DEBUG] > Connector Init
[2017-11-02 14:05:23,448|NsdManageService.py:30][INFO] > ===============================================
[2017-11-02 14:05:23,448|NsdManageService.py:31][INFO] > [WEB] -> RESTIF
[2017-11-02 14:05:23,448|NsdManageService.py:32][INFO] > ===============================================
[2017-11-02 14:05:23,453|NsdManageService.py:33][INFO] > REQUEST URL : http://175.213.170.13:8500/ns_descriptors
[2017-11-02 14:05:23,453|NsdManageService.py:34][INFO] > BODY : {u'age': 123, u'name': u'hoho'}
[2017-11-02 14:05:23,453|NsdManageService.py:35][INFO] > ===============================================
[2017-11-02 14:05:23,454|PLTEConnector.py:68][INFO] > ===============================================
[2017-11-02 14:05:23,454|PLTEConnector.py:69][INFO] > RESTIF -> PLTEIB
[2017-11-02 14:05:23,454|PLTEConnector.py:70][INFO] > ===============================================
[2017-11-02 14:05:23,454|PLTEConnector.py:71][INFO] > API_NAME : nsd-on-boarding
[2017-11-02 14:05:23,455|PLTEConnector.py:72][INFO] > PID   : 1
[2017-11-02 14:05:23,455|PLTEConnector.py:73][INFO] > BODY   : temp
[2017-11-02 14:05:23,455|PLTEConnector.py:74][INFO] > ===============================================
[2017-11-02 14:10:45,468|ReqReceiver.py:34][ERROR] > ReqReceiver Init
[2017-11-02 14:10:45,469|ResReceiver.py:33][INFO] > ResReceiver Init
[2017-11-02 14:10:45,469|PLTEConnector.py:28][DEBUG] > PLTEConnector Init
[2017-11-02 14:10:45,469|PLTEManager.py:22][DEBUG] > PLTE Manager Init
[2017-11-02 14:10:45,469|Connector.py:25][DEBUG] > Connector Init
[2017-11-02 14:10:49,488|NsdManageService.py:30][INFO] > ===============================================
[2017-11-02 14:10:49,488|NsdManageService.py:31][INFO] > [WEB] -> RESTIF
[2017-11-02 14:10:49,488|NsdManageService.py:32][INFO] > ===============================================
[2017-11-02 14:10:49,493|NsdManageService.py:33][INFO] > REQUEST URL : http://175.213.170.13:8500/ns_descriptors
[2017-11-02 14:10:49,493|NsdManageService.py:34][INFO] > BODY : {u'age': 123, u'name': u'hoho'}
[2017-11-02 14:10:49,494|NsdManageService.py:35][INFO] > ===============================================
[2017-11-02 14:10:49,497|PLTEConnector.py:68][INFO] > ===============================================
[2017-11-02 14:10:49,498|PLTEConnector.py:69][INFO] > RESTIF -> PLTEIB
[2017-11-02 14:10:49,498|PLTEConnector.py:70][INFO] > ===============================================
[2017-11-02 14:10:49,498|PLTEConnector.py:71][INFO] > API_NAME : nsd-on-boarding
[2017-11-02 14:10:49,498|PLTEConnector.py:72][INFO] > PID   : 1
[2017-11-02 14:10:49,498|PLTEConnector.py:73][INFO] > BODY   : temp
[2017-11-02 14:10:49,498|PLTEConnector.py:74][INFO] > ===============================================
[2017-11-02 14:10:50,499|ResReceiver.py:77][INFO] > ===============================================
[2017-11-02 14:10:50,499|ResReceiver.py:78][INFO] > [APP] -> RESTIF
[2017-11-02 14:10:50,499|ResReceiver.py:79][INFO] > ===============================================
[2017-11-02 14:10:50,500|ResReceiver.py:80][INFO] > msgType: 600
[2017-11-02 14:10:50,500|ResReceiver.py:81][INFO] > tot_len : 100
[2017-11-02 14:10:50,500|ResReceiver.py:82][INFO] > msgId : 1
[2017-11-02 14:10:50,500|ResReceiver.py:83][INFO] > ehttp_idx : 71
[2017-11-02 14:10:50,500|ResReceiver.py:84][INFO] > srcQid : 300
[2017-11-02 14:10:50,500|ResReceiver.py:85][INFO] > srcSysId : 1
[2017-11-02 14:10:50,500|ResReceiver.py:86][INFO] > nResult : 200
[2017-11-02 14:10:50,500|ResReceiver.py:87][INFO] > jsonBody: temp
[2017-11-02 14:10:50,500|ResReceiver.py:88][INFO] > ===============================================
[2017-11-02 14:10:50,500|ResReceiver.py:89][INFO] > method: 1
[2017-11-02 14:10:50,501|ResReceiver.py:90][INFO] > api_type: 2
[2017-11-02 14:10:50,501|ResReceiver.py:91][INFO] > op_type: 3
[2017-11-02 14:10:50,501|ResReceiver.py:92][INFO] > length: 4
[2017-11-02 14:10:50,501|ResReceiver.py:93][INFO] > encoding: 5
[2017-11-02 14:10:50,501|ResReceiver.py:94][INFO] > ===============================================
[2017-11-02 14:10:51,500|NsdManageService.py:56][INFO] > ===============================================
[2017-11-02 14:10:51,501|NsdManageService.py:57][INFO] > RESTIF -> [WEB]
[2017-11-02 14:10:51,501|NsdManageService.py:58][INFO] > ===============================================
[2017-11-02 14:10:51,501|NsdManageService.py:59][INFO] > TID : 1
[2017-11-02 14:10:51,501|NsdManageService.py:60][INFO] > RESCODE : 200
[2017-11-02 14:10:51,501|NsdManageService.py:62][INFO] > ===============================================
[2017-11-02 14:41:44,221|ReqReceiver.py:34][ERROR] > ReqReceiver Init
[2017-11-02 14:41:44,223|ResReceiver.py:33][INFO] > ResReceiver Init
[2017-11-02 14:41:44,223|PLTEConnector.py:28][DEBUG] > PLTEConnector Init
[2017-11-02 14:41:44,223|PLTEManager.py:22][DEBUG] > PLTE Manager Init
[2017-11-02 14:41:44,224|Connector.py:25][DEBUG] > Connector Init
[2017-11-02 14:42:07,343|ReqReceiver.py:34][ERROR] > ReqReceiver Init
[2017-11-02 14:42:07,343|ResReceiver.py:33][INFO] > ResReceiver Init
[2017-11-02 14:42:07,344|PLTEConnector.py:28][DEBUG] > PLTEConnector Init
[2017-11-02 14:42:07,344|PLTEManager.py:22][DEBUG] > PLTE Manager Init
[2017-11-02 14:42:07,344|Connector.py:25][DEBUG] > Connector Init
[2017-11-02 14:42:07,344|PLTEConnector.py:35][ERROR] > msgQueue Connection Failed.. PLTE QUEUE_ID[12345]
[2017-11-02 14:42:45,933|ReqReceiver.py:34][ERROR] > ReqReceiver Init
[2017-11-02 14:42:45,934|ResReceiver.py:33][INFO] > ResReceiver Init
[2017-11-02 14:42:45,934|PLTEConnector.py:28][DEBUG] > PLTEConnector Init
[2017-11-02 14:42:45,934|PLTEManager.py:22][DEBUG] > PLTE Manager Init
[2017-11-02 14:42:45,935|Connector.py:25][DEBUG] > Connector Init
[2017-11-02 14:42:45,935|PLTEConnector.py:35][ERROR] > msgQueue Connection Failed.. PLTE QUEUE_ID[12345]
[2017-11-02 14:48:36,074|ClientService.py:34][INFO] > ===============================================
[2017-11-02 14:48:36,075|ClientService.py:35][INFO] > RESTIF -> [EXT]
[2017-11-02 14:48:36,075|ClientService.py:36][INFO] > ===============================================
[2017-11-02 14:48:36,075|ClientService.py:37][INFO] > URL : http://localhost:5000/departments/abc/123
[2017-11-02 14:48:36,075|ClientService.py:38][INFO] > TID : tid
[2017-11-02 14:48:50,675|ClientService.py:34][INFO] > ===============================================
[2017-11-02 14:48:50,675|ClientService.py:35][INFO] > RESTIF -> [EXT]
[2017-11-02 14:48:50,675|ClientService.py:36][INFO] > ===============================================
[2017-11-02 14:48:50,676|ClientService.py:37][INFO] > URL : http://localhost:5000/departments/abc/123
[2017-11-02 14:48:50,676|ClientService.py:38][INFO] > TID : tid
[2017-11-02 14:55:46,726|ReqReceiver.py:34][ERROR] > ReqReceiver Init
[2017-11-02 14:55:46,727|ResReceiver.py:33][INFO] > ResReceiver Init
[2017-11-02 14:55:46,728|PLTEConnector.py:28][DEBUG] > PLTEConnector Init
[2017-11-02 14:55:46,728|PLTEManager.py:22][DEBUG] > PLTE Manager Init
[2017-11-02 14:55:46,728|Connector.py:25][DEBUG] > Connector Init
[2017-11-02 14:55:52,634|ClientService.py:34][INFO] > ===============================================
[2017-11-02 14:55:52,634|ClientService.py:35][INFO] > RESTIF -> [EXT]
[2017-11-02 14:55:52,634|ClientService.py:36][INFO] > ===============================================
[2017-11-02 14:55:52,634|ClientService.py:37][INFO] > URL : http://localhost:5555/departments/abc/123
[2017-11-02 14:55:52,635|ClientService.py:38][INFO] > TID : tid
[2017-11-02 14:55:52,635|ClientService.py:39][INFO] > HEADER : {'Content-type': 'application/json', 'Accept': 'application/json'}
[2017-11-02 14:55:52,635|ClientService.py:40][INFO] > BODY : {'age': 123, 'name': 'Hoyoung'}
[2017-11-02 14:55:52,635|ClientService.py:41][INFO] > ===============================================
[2017-11-02 14:55:52,660|ClientService.py:54][INFO] > ===============================================
[2017-11-02 14:55:52,660|ClientService.py:55][INFO] > [EXT] -> RESTIF
[2017-11-02 14:55:52,660|ClientService.py:56][INFO] > ===============================================
[2017-11-02 14:55:52,660|ClientService.py:57][INFO] > URL : http://localhost:5555/departments/abc/123
[2017-11-02 14:55:52,660|ClientService.py:58][INFO] > TID : tid
[2017-11-02 14:55:52,660|ClientService.py:59][INFO] > RESULT : 200
[2017-11-02 14:55:52,661|ClientService.py:60][INFO] > HEADER : {'date': 'Thu, 02 Nov 2017 05:55:52 GMT', 'content-length': '74', 'content-type': 'application/json', 'server': 'Werkzeug/0.12.2 Python/2.7.5'}
[2017-11-02 14:55:52,730|ClientService.py:61][INFO] > BODY : {
  "abc": 123, 
  "age": 123, 
  "d_name": "abc", 
  "name": "Hoyoung"
}

[2017-11-02 14:55:52,730|ClientService.py:62][INFO] > ===============================================
[2017-11-02 15:33:56,977|ReqReceiver.py:34][ERROR] > ReqReceiver Init
[2017-11-02 15:33:56,979|ResReceiver.py:33][INFO] > ResReceiver Init
[2017-11-02 15:33:56,979|PLTEConnector.py:28][DEBUG] > PLTEConnector Init
[2017-11-02 15:33:56,980|PLTEManager.py:22][DEBUG] > PLTE Manager Init
[2017-11-02 15:33:56,980|Connector.py:25][DEBUG] > Connector Init
[2017-11-02 15:34:12,534|ReqReceiver.py:34][ERROR] > ReqReceiver Init
[2017-11-02 15:34:12,535|ResReceiver.py:33][INFO] > ResReceiver Init
[2017-11-02 15:34:12,535|PLTEConnector.py:28][DEBUG] > PLTEConnector Init
[2017-11-02 15:34:12,535|PLTEManager.py:22][DEBUG] > PLTE Manager Init
[2017-11-02 15:34:12,535|Connector.py:25][DEBUG] > Connector Init
[2017-11-02 15:34:15,981|ClientService.py:35][INFO] > ===============================================
[2017-11-02 15:34:15,981|ClientService.py:36][INFO] > RESTIF -> [EXT]
[2017-11-02 15:34:15,981|ClientService.py:37][INFO] > ===============================================
[2017-11-02 15:34:15,982|ClientService.py:38][INFO] > URL : http://localhost:5555/departments/abc/123
[2017-11-02 15:35:04,245|ReqReceiver.py:34][ERROR] > ReqReceiver Init
[2017-11-02 15:35:04,246|ResReceiver.py:33][INFO] > ResReceiver Init
[2017-11-02 15:35:04,246|PLTEConnector.py:28][DEBUG] > PLTEConnector Init
[2017-11-02 15:35:04,247|PLTEManager.py:22][DEBUG] > PLTE Manager Init
[2017-11-02 15:35:04,247|Connector.py:25][DEBUG] > Connector Init
[2017-11-02 15:35:13,537|ClientService.py:35][INFO] > ===============================================
[2017-11-02 15:35:13,537|ClientService.py:36][INFO] > RESTIF -> [EXT]
[2017-11-02 15:35:13,538|ClientService.py:37][INFO] > ===============================================
[2017-11-02 15:35:13,538|ClientService.py:38][INFO] > URL : http://localhost:5555/departments/abc/123
[2017-11-02 15:35:13,538|ClientService.py:39][INFO] > TID : 200
[2017-11-02 15:35:13,538|ClientService.py:40][INFO] > HEADER : {'Content-type': 'application/json', 'Accept': 'application/json'}
[2017-11-02 15:35:13,538|ClientService.py:41][INFO] > BODY : {'name':'Hoyoung', 'age': 123 }
[2017-11-02 15:35:13,538|ClientService.py:42][INFO] > ===============================================
[2017-11-02 15:35:13,562|ClientService.py:55][INFO] > ===============================================
[2017-11-02 15:35:13,562|ClientService.py:56][INFO] > [EXT] -> RESTIF
[2017-11-02 15:35:13,563|ClientService.py:57][INFO] > ===============================================
[2017-11-02 15:35:13,563|ClientService.py:58][INFO] > URL : http://localhost:5555/departments/abc/123
[2017-11-02 15:35:13,563|ClientService.py:59][INFO] > TID : 200
[2017-11-02 15:35:13,563|ClientService.py:60][INFO] > RESULT : 500
[2017-11-02 15:35:13,563|ClientService.py:61][INFO] > HEADER : {'date': 'Thu, 02 Nov 2017 06:35:13 GMT', 'content-length': '37', 'content-type': 'application/json', 'server': 'Werkzeug/0.12.2 Python/2.7.5'}
[2017-11-02 15:35:13,570|ClientService.py:62][INFO] > BODY : {"message": "Internal Server Error"}

[2017-11-02 15:35:13,570|ClientService.py:63][INFO] > ===============================================
[2017-11-02 15:36:07,236|ReqReceiver.py:34][ERROR] > ReqReceiver Init
[2017-11-02 15:36:07,237|ResReceiver.py:33][INFO] > ResReceiver Init
[2017-11-02 15:36:07,237|PLTEConnector.py:28][DEBUG] > PLTEConnector Init
[2017-11-02 15:36:07,237|PLTEManager.py:22][DEBUG] > PLTE Manager Init
[2017-11-02 15:36:07,238|Connector.py:25][DEBUG] > Connector Init
[2017-11-02 15:36:09,341|ClientService.py:35][INFO] > ===============================================
[2017-11-02 15:36:09,342|ClientService.py:36][INFO] > RESTIF -> [EXT]
[2017-11-02 15:36:09,342|ClientService.py:37][INFO] > ===============================================
[2017-11-02 15:36:09,342|ClientService.py:38][INFO] > URL : http://localhost:5555/departments/abc/123
[2017-11-02 15:36:09,342|ClientService.py:39][INFO] > TID : 200
[2017-11-02 15:36:09,342|ClientService.py:40][INFO] > HEADER : {'Content-type': 'application/json', 'Accept': 'application/json'}
[2017-11-02 15:36:09,342|ClientService.py:41][INFO] > BODY : {'name':'Hoyoung', 'age': 123 }
[2017-11-02 15:36:09,342|ClientService.py:42][INFO] > ===============================================
[2017-11-02 15:36:09,366|ClientService.py:55][INFO] > ===============================================
[2017-11-02 15:36:09,367|ClientService.py:56][INFO] > [EXT] -> RESTIF
[2017-11-02 15:36:09,367|ClientService.py:57][INFO] > ===============================================
[2017-11-02 15:36:09,367|ClientService.py:58][INFO] > URL : http://localhost:5555/departments/abc/123
[2017-11-02 15:36:09,367|ClientService.py:59][INFO] > TID : 200
[2017-11-02 15:36:09,367|ClientService.py:60][INFO] > RESULT : 500
[2017-11-02 15:36:09,367|ClientService.py:61][INFO] > HEADER : {'date': 'Thu, 02 Nov 2017 06:36:09 GMT', 'content-length': '37', 'content-type': 'application/json', 'server': 'Werkzeug/0.12.2 Python/2.7.5'}
[2017-11-02 15:36:09,374|ClientService.py:62][INFO] > BODY : {"message": "Internal Server Error"}

[2017-11-02 15:36:09,374|ClientService.py:63][INFO] > ===============================================
[2017-11-02 15:39:19,585|ReqReceiver.py:34][ERROR] > ReqReceiver Init
[2017-11-02 15:39:19,586|ResReceiver.py:33][INFO] > ResReceiver Init
[2017-11-02 15:39:19,586|PLTEConnector.py:28][DEBUG] > PLTEConnector Init
[2017-11-02 15:39:19,586|PLTEManager.py:22][DEBUG] > PLTE Manager Init
[2017-11-02 15:39:19,586|Connector.py:25][DEBUG] > Connector Init
[2017-11-02 15:39:22,988|ClientService.py:35][INFO] > ===============================================
[2017-11-02 15:39:22,988|ClientService.py:36][INFO] > RESTIF -> [EXT]
[2017-11-02 15:39:22,989|ClientService.py:37][INFO] > ===============================================
[2017-11-02 15:39:22,989|ClientService.py:38][INFO] > URL : http://localhost:5555/departments/abc/123
[2017-11-02 15:39:22,989|ClientService.py:39][INFO] > TID : 200
[2017-11-02 15:39:22,989|ClientService.py:40][INFO] > HEADER : {'Content-type': 'application/json', 'Accept': 'application/json'}
[2017-11-02 15:39:22,989|ClientService.py:41][INFO] > BODY : {'name':'Hoyoung', 'age': 123 }
[2017-11-02 15:39:22,989|ClientService.py:42][INFO] > ===============================================
[2017-11-02 15:39:23,012|ClientService.py:55][INFO] > ===============================================
[2017-11-02 15:39:23,012|ClientService.py:56][INFO] > [EXT] -> RESTIF
[2017-11-02 15:39:23,012|ClientService.py:57][INFO] > ===============================================
[2017-11-02 15:39:23,012|ClientService.py:58][INFO] > URL : http://localhost:5555/departments/abc/123
[2017-11-02 15:39:23,012|ClientService.py:59][INFO] > TID : 200
[2017-11-02 15:39:23,012|ClientService.py:60][INFO] > RESULT : 500
[2017-11-02 15:39:23,013|ClientService.py:61][INFO] > HEADER : {'date': 'Thu, 02 Nov 2017 06:39:23 GMT', 'content-length': '37', 'content-type': 'application/json', 'server': 'Werkzeug/0.12.2 Python/2.7.5'}
[2017-11-02 15:39:23,019|ClientService.py:62][INFO] > BODY : {"message": "Internal Server Error"}

[2017-11-02 15:39:23,019|ClientService.py:63][INFO] > ===============================================
[2017-11-02 15:43:28,220|ReqReceiver.py:34][ERROR] > ReqReceiver Init
[2017-11-02 15:43:28,222|ResReceiver.py:33][INFO] > ResReceiver Init
[2017-11-02 15:43:28,222|PLTEConnector.py:28][DEBUG] > PLTEConnector Init
[2017-11-02 15:43:28,222|PLTEManager.py:22][DEBUG] > PLTE Manager Init
[2017-11-02 15:43:28,223|Connector.py:25][DEBUG] > Connector Init
[2017-11-02 15:43:32,788|ClientService.py:35][INFO] > ===============================================
[2017-11-02 15:43:32,789|ClientService.py:36][INFO] > RESTIF -> [EXT]
[2017-11-02 15:43:32,789|ClientService.py:37][INFO] > ===============================================
[2017-11-02 15:43:32,789|ClientService.py:38][INFO] > URL : http://localhost:5555/departments/abc/123
[2017-11-02 15:43:32,789|ClientService.py:39][INFO] > TID : 200
[2017-11-02 15:43:32,789|ClientService.py:40][INFO] > HEADER : {'Content-type': 'application/json', 'Accept': 'application/json'}
[2017-11-02 15:43:32,789|ClientService.py:41][INFO] > BODY : {'name':'Hoyoung', 'age': 123 }
[2017-11-02 15:43:32,789|ClientService.py:42][INFO] > ===============================================
[2017-11-02 15:43:32,814|ClientService.py:55][INFO] > ===============================================
[2017-11-02 15:43:32,814|ClientService.py:56][INFO] > [EXT] -> RESTIF
[2017-11-02 15:43:32,814|ClientService.py:57][INFO] > ===============================================
[2017-11-02 15:43:32,815|ClientService.py:58][INFO] > URL : http://localhost:5555/departments/abc/123
[2017-11-02 15:43:32,815|ClientService.py:59][INFO] > TID : 200
[2017-11-02 15:43:32,815|ClientService.py:60][INFO] > RESULT : 500
[2017-11-02 15:43:32,815|ClientService.py:61][INFO] > HEADER : {'date': 'Thu, 02 Nov 2017 06:43:32 GMT', 'content-length': '37', 'content-type': 'application/json', 'server': 'Werkzeug/0.12.2 Python/2.7.5'}
[2017-11-02 15:43:32,821|ClientService.py:62][INFO] > BODY : {"message": "Internal Server Error"}

[2017-11-02 15:43:32,821|ClientService.py:63][INFO] > ===============================================
[2017-11-02 15:43:32,822|PLTEConnector.py:93][INFO] > ===============================================
[2017-11-02 15:43:32,822|PLTEConnector.py:94][INFO] > RESTIF -> PLTEIB
[2017-11-02 15:43:32,822|PLTEConnector.py:95][INFO] > ===============================================
[2017-11-02 15:43:32,822|PLTEConnector.py:96][INFO] > COMMAND : http://localhost:5555/departments/abc/123
[2017-11-02 15:43:32,822|PLTEConnector.py:97][INFO] > RESTCODE : 500
[2017-11-02 15:43:32,822|PLTEConnector.py:99][INFO] > BODY   : {"message": "Internal Server Error"}

[2017-11-02 15:43:32,823|PLTEConnector.py:100][INFO] > ===============================================
[2017-11-02 15:46:15,562|ReqReceiver.py:34][ERROR] > ReqReceiver Init
[2017-11-02 15:46:15,563|ResReceiver.py:33][INFO] > ResReceiver Init
[2017-11-02 15:46:15,563|PLTEConnector.py:28][DEBUG] > PLTEConnector Init
[2017-11-02 15:46:15,563|PLTEManager.py:22][DEBUG] > PLTE Manager Init
[2017-11-02 15:46:15,563|Connector.py:25][DEBUG] > Connector Init
[2017-11-02 15:46:15,563|PLTEConnector.py:35][ERROR] > msgQueue Connection Failed.. PLTE QUEUE_ID[12345]
[2017-11-02 15:47:12,574|ReqReceiver.py:34][ERROR] > ReqReceiver Init
[2017-11-02 15:47:12,575|ResReceiver.py:33][INFO] > ResReceiver Init
[2017-11-02 15:47:12,576|PLTEConnector.py:28][DEBUG] > PLTEConnector Init
[2017-11-02 15:47:12,576|PLTEManager.py:22][DEBUG] > PLTE Manager Init
[2017-11-02 15:47:12,576|Connector.py:25][DEBUG] > Connector Init
[2017-11-02 15:47:17,160|ClientService.py:34][INFO] > ===============================================
[2017-11-02 15:47:17,161|ClientService.py:35][INFO] > RESTIF -> [EXT]
[2017-11-02 15:47:17,161|ClientService.py:36][INFO] > ===============================================
[2017-11-02 15:47:17,161|ClientService.py:37][INFO] > URL : http://localhost:5555/departments/abc/123
[2017-11-02 15:47:17,161|ClientService.py:38][INFO] > TID : 200
[2017-11-02 15:47:17,161|ClientService.py:39][INFO] > HEADER : {'Content-type': 'application/json', 'Accept': 'application/json'}
[2017-11-02 15:47:17,161|ClientService.py:40][INFO] > BODY : 
[2017-11-02 15:47:17,161|ClientService.py:41][INFO] > ===============================================
[2017-11-02 15:47:17,189|ClientService.py:54][INFO] > ===============================================
[2017-11-02 15:47:17,189|ClientService.py:55][INFO] > [EXT] -> RESTIF
[2017-11-02 15:47:17,189|ClientService.py:56][INFO] > ===============================================
[2017-11-02 15:47:17,189|ClientService.py:57][INFO] > URL : http://localhost:5555/departments/abc/123
[2017-11-02 15:47:17,189|ClientService.py:58][INFO] > TID : 200
[2017-11-02 15:47:17,189|ClientService.py:59][INFO] > RESULT : 500
[2017-11-02 15:47:17,189|ClientService.py:60][INFO] > HEADER : {'date': 'Thu, 02 Nov 2017 06:47:17 GMT', 'content-length': '37', 'content-type': 'application/json', 'server': 'Werkzeug/0.12.2 Python/2.7.5'}
[2017-11-02 15:47:17,196|ClientService.py:61][INFO] > BODY : {"message": "Internal Server Error"}

[2017-11-02 15:47:17,196|ClientService.py:62][INFO] > ===============================================
[2017-11-02 15:47:17,197|PLTEConnector.py:93][INFO] > ===============================================
[2017-11-02 15:47:17,197|PLTEConnector.py:94][INFO] > RESTIF -> PLTEIB
[2017-11-02 15:47:17,197|PLTEConnector.py:95][INFO] > ===============================================
[2017-11-02 15:47:17,197|PLTEConnector.py:96][INFO] > COMMAND : http://localhost:5555/departments/abc/123
[2017-11-02 15:47:17,197|PLTEConnector.py:97][INFO] > RESTCODE : 500
[2017-11-02 15:47:17,197|PLTEConnector.py:99][INFO] > BODY   : {"message": "Internal Server Error"}

[2017-11-02 15:47:17,197|PLTEConnector.py:100][INFO] > ===============================================
[2017-11-02 15:55:17,620|ReqReceiver.py:34][ERROR] > ReqReceiver Init
[2017-11-02 15:55:17,621|ResReceiver.py:33][INFO] > ResReceiver Init
[2017-11-02 15:55:17,622|PLTEConnector.py:28][DEBUG] > PLTEConnector Init
[2017-11-02 15:55:17,622|PLTEManager.py:22][DEBUG] > PLTE Manager Init
[2017-11-02 15:55:17,622|Connector.py:25][DEBUG] > Connector Init
[2017-11-02 15:55:22,019|ReqReceiver.py:73][INFO] > ===============================================
[2017-11-02 15:55:22,019|ReqReceiver.py:74][INFO] > [APP] -> RESTIF
[2017-11-02 15:55:22,019|ReqReceiver.py:75][INFO] > ===============================================
[2017-11-02 15:55:22,019|ReqReceiver.py:76][INFO] > msgType: 500
[2017-11-02 15:55:22,019|ReqReceiver.py:77][INFO] > tot_len : 100
[2017-11-02 15:55:22,019|ReqReceiver.py:78][INFO] > msgId : 200
[2017-11-02 15:55:22,019|ReqReceiver.py:79][INFO] > ehttp_idx : 300
[2017-11-02 15:55:22,020|ReqReceiver.py:80][INFO] > srcQid : 400
[2017-11-02 15:55:22,020|ReqReceiver.py:81][INFO] > srcSysId : 5
[2017-11-02 15:55:22,020|ReqReceiver.py:97][ERROR] > Msgrcv Failed..  'HttpReq' object has no attribute 'nResult'
[2017-11-02 15:56:03,180|ReqReceiver.py:34][ERROR] > ReqReceiver Init
[2017-11-02 15:56:03,181|ResReceiver.py:33][INFO] > ResReceiver Init
[2017-11-02 15:56:03,181|PLTEConnector.py:28][DEBUG] > PLTEConnector Init
[2017-11-02 15:56:03,181|PLTEManager.py:22][DEBUG] > PLTE Manager Init
[2017-11-02 15:56:03,181|Connector.py:25][DEBUG] > Connector Init
[2017-11-02 15:56:07,210|ReqReceiver.py:73][INFO] > ===============================================
[2017-11-02 15:56:07,211|ReqReceiver.py:74][INFO] > [APP] -> RESTIF
[2017-11-02 15:56:07,211|ReqReceiver.py:75][INFO] > ===============================================
[2017-11-02 15:56:07,211|ReqReceiver.py:76][INFO] > msgType: 500
[2017-11-02 15:56:07,211|ReqReceiver.py:77][INFO] > tot_len : 100
[2017-11-02 15:56:07,211|ReqReceiver.py:78][INFO] > msgId : 200
[2017-11-02 15:56:07,211|ReqReceiver.py:79][INFO] > ehttp_idx : 300
[2017-11-02 15:56:07,211|ReqReceiver.py:80][INFO] > srcQid : 400
[2017-11-02 15:56:07,211|ReqReceiver.py:81][INFO] > srcSysId : 5
[2017-11-02 15:56:07,211|ReqReceiver.py:82][INFO] > jsonBody: 
[2017-11-02 15:56:07,212|ReqReceiver.py:83][INFO] > ===============================================
[2017-11-02 15:56:07,212|ReqReceiver.py:84][INFO] > method: 1
[2017-11-02 15:56:07,212|ReqReceiver.py:85][INFO] > api_type: 2
[2017-11-02 15:56:07,212|ReqReceiver.py:86][INFO] > op_type: 3
[2017-11-02 15:56:07,212|ReqReceiver.py:87][INFO] > length: 4
[2017-11-02 15:56:07,212|ReqReceiver.py:88][INFO] > encoding: 
[2017-11-02 15:56:07,212|ReqReceiver.py:89][INFO] > ===============================================
[2017-11-02 15:56:07,213|ClientService.py:34][INFO] > ===============================================
[2017-11-02 15:56:07,214|ClientService.py:35][INFO] > RESTIF -> [EXT]
[2017-11-02 15:56:07,214|ClientService.py:36][INFO] > ===============================================
[2017-11-02 15:56:07,214|ClientService.py:37][INFO] > URL : http://localhost:5555/departments/abc/123
[2017-11-02 15:56:07,214|ClientService.py:38][INFO] > HEADER : {'Content-type': 'application/json', 'Accept': 'application/json'}
[2017-11-02 15:56:07,214|ClientService.py:39][INFO] > TID : 200
[2017-11-02 15:56:07,214|ClientService.py:40][INFO] > BODY : 
[2017-11-02 15:56:07,214|ClientService.py:41][INFO] > ===============================================
[2017-11-02 15:56:07,238|ClientService.py:54][INFO] > ===============================================
[2017-11-02 15:56:07,238|ClientService.py:55][INFO] > [EXT] -> RESTIF
[2017-11-02 15:56:07,238|ClientService.py:56][INFO] > ===============================================
[2017-11-02 15:56:07,238|ClientService.py:57][INFO] > URL : http://localhost:5555/departments/abc/123
[2017-11-02 15:56:07,238|ClientService.py:58][INFO] > TID : 200
[2017-11-02 15:56:07,239|ClientService.py:59][INFO] > RESULT : 500
[2017-11-02 15:56:07,239|ClientService.py:60][INFO] > HEADER : {'date': 'Thu, 02 Nov 2017 06:56:07 GMT', 'content-length': '37', 'content-type': 'application/json', 'server': 'Werkzeug/0.12.2 Python/2.7.5'}
[2017-11-02 15:56:07,245|ClientService.py:61][INFO] > BODY : {"message": "Internal Server Error"}

[2017-11-02 15:56:07,245|ClientService.py:62][INFO] > ===============================================
[2017-11-02 15:56:07,246|PLTEConnector.py:93][INFO] > ===============================================
[2017-11-02 15:56:07,246|PLTEConnector.py:94][INFO] > RESTIF -> [APP]
[2017-11-02 15:56:07,246|PLTEConnector.py:95][INFO] > ===============================================
[2017-11-02 15:56:07,246|PLTEConnector.py:96][INFO] > API_NAME : http://localhost:5555/departments/abc/123
[2017-11-02 15:56:07,246|PLTEConnector.py:97][INFO] > PID   : 200
[2017-11-02 15:56:07,246|PLTEConnector.py:98][INFO] > RESTCODE : 500
[2017-11-02 15:56:07,246|PLTEConnector.py:99][INFO] > BODY   : {"message": "Internal Server Error"}

[2017-11-02 15:56:07,246|PLTEConnector.py:100][INFO] > ===============================================
[2017-11-02 15:57:58,700|ReqReceiver.py:34][ERROR] > ReqReceiver Init
[2017-11-02 15:57:58,700|ResReceiver.py:33][INFO] > ResReceiver Init
[2017-11-02 15:57:58,701|PLTEConnector.py:28][DEBUG] > PLTEConnector Init
[2017-11-02 15:57:58,701|PLTEManager.py:22][DEBUG] > PLTE Manager Init
[2017-11-02 15:57:58,701|Connector.py:25][DEBUG] > Connector Init
[2017-11-02 15:57:58,701|PLTEConnector.py:35][ERROR] > msgQueue Connection Failed.. PLTE QUEUE_ID[12345]
[2017-11-02 15:58:03,015|ReqReceiver.py:73][INFO] > ===============================================
[2017-11-02 15:58:03,016|ReqReceiver.py:74][INFO] > [APP] -> RESTIF
[2017-11-02 15:58:03,016|ReqReceiver.py:75][INFO] > ===============================================
[2017-11-02 15:58:03,016|ReqReceiver.py:76][INFO] > msgType: 500
[2017-11-02 15:58:03,016|ReqReceiver.py:77][INFO] > tot_len : 100
[2017-11-02 15:58:03,016|ReqReceiver.py:78][INFO] > msgId : 200
[2017-11-02 15:58:03,016|ReqReceiver.py:79][INFO] > ehttp_idx : 300
[2017-11-02 15:58:03,016|ReqReceiver.py:80][INFO] > srcQid : 400
[2017-11-02 15:58:03,017|ReqReceiver.py:81][INFO] > srcSysId : 5
[2017-11-02 15:58:03,017|ReqReceiver.py:82][INFO] > jsonBody: {'name':'Hoyoung', 'age': 123 }
[2017-11-02 15:58:03,017|ReqReceiver.py:83][INFO] > ===============================================
[2017-11-02 15:58:03,017|ReqReceiver.py:84][INFO] > method: 1
[2017-11-02 15:58:03,017|ReqReceiver.py:85][INFO] > api_type: 2
[2017-11-02 15:58:03,017|ReqReceiver.py:86][INFO] > op_type: 3
[2017-11-02 15:58:03,017|ReqReceiver.py:87][INFO] > length: 4
[2017-11-02 15:58:03,017|ReqReceiver.py:88][INFO] > encoding: 
[2017-11-02 15:58:03,017|ReqReceiver.py:89][INFO] > ===============================================
[2017-11-02 15:58:03,018|ClientService.py:34][INFO] > ===============================================
[2017-11-02 15:58:03,018|ClientService.py:35][INFO] > RESTIF -> [EXT]
[2017-11-02 15:58:03,018|ClientService.py:36][INFO] > ===============================================
[2017-11-02 15:58:03,018|ClientService.py:37][INFO] > URL : http://localhost:5555/departments/abc/123
[2017-11-02 15:58:03,019|ClientService.py:38][INFO] > HEADER : {'Content-type': 'application/json', 'Accept': 'application/json'}
[2017-11-02 15:58:03,019|ClientService.py:39][INFO] > TID : 200
[2017-11-02 15:58:03,019|ClientService.py:40][INFO] > BODY : {'name':'Hoyoung', 'age': 123 }
[2017-11-02 15:58:03,019|ClientService.py:41][INFO] > ===============================================
[2017-11-02 15:58:03,045|ClientService.py:54][INFO] > ===============================================
[2017-11-02 15:58:03,045|ClientService.py:55][INFO] > [EXT] -> RESTIF
[2017-11-02 15:58:03,046|ClientService.py:56][INFO] > ===============================================
[2017-11-02 15:58:03,046|ClientService.py:57][INFO] > URL : http://localhost:5555/departments/abc/123
[2017-11-02 15:58:03,046|ClientService.py:58][INFO] > TID : 200
[2017-11-02 15:58:03,046|ClientService.py:59][INFO] > RESULT : 500
[2017-11-02 15:58:03,046|ClientService.py:60][INFO] > HEADER : {'date': 'Thu, 02 Nov 2017 06:58:03 GMT', 'content-length': '37', 'content-type': 'application/json', 'server': 'Werkzeug/0.12.2 Python/2.7.5'}
[2017-11-02 15:58:03,052|ClientService.py:61][INFO] > BODY : {"message": "Internal Server Error"}

[2017-11-02 15:58:03,052|ClientService.py:62][INFO] > ===============================================
[2017-11-02 15:58:03,054|PLTEConnector.py:89][ERROR] > sendMessage Error! 'PLTEConnector' object has no attribute 'plteQueue'
[2017-11-02 16:00:48,657|ReqReceiver.py:34][ERROR] > ReqReceiver Init
[2017-11-02 16:00:48,658|ResReceiver.py:33][INFO] > ResReceiver Init
[2017-11-02 16:00:48,658|PLTEConnector.py:28][DEBUG] > PLTEConnector Init
[2017-11-02 16:00:48,658|PLTEManager.py:22][DEBUG] > PLTE Manager Init
[2017-11-02 16:00:48,658|Connector.py:25][DEBUG] > Connector Init
[2017-11-02 16:00:48,658|PLTEConnector.py:35][ERROR] > msgQueue Connection Failed.. PLTE QUEUE_ID[12345]
[2017-11-02 16:00:52,310|ReqReceiver.py:73][INFO] > ===============================================
[2017-11-02 16:00:52,311|ReqReceiver.py:74][INFO] > [APP] -> RESTIF
[2017-11-02 16:00:52,311|ReqReceiver.py:75][INFO] > ===============================================
[2017-11-02 16:00:52,311|ReqReceiver.py:76][INFO] > msgType: 500
[2017-11-02 16:00:52,311|ReqReceiver.py:77][INFO] > tot_len : 100
[2017-11-02 16:00:52,311|ReqReceiver.py:78][INFO] > msgId : 200
[2017-11-02 16:00:52,311|ReqReceiver.py:79][INFO] > ehttp_idx : 300
[2017-11-02 16:00:52,311|ReqReceiver.py:80][INFO] > srcQid : 400
[2017-11-02 16:00:52,311|ReqReceiver.py:81][INFO] > srcSysId : 5
[2017-11-02 16:00:52,311|ReqReceiver.py:82][INFO] > jsonBody: {"name":"Hoyoung", "age": 123 }
[2017-11-02 16:00:52,311|ReqReceiver.py:83][INFO] > ===============================================
[2017-11-02 16:00:52,311|ReqReceiver.py:84][INFO] > method: 1
[2017-11-02 16:00:52,312|ReqReceiver.py:85][INFO] > api_type: 2
[2017-11-02 16:00:52,312|ReqReceiver.py:86][INFO] > op_type: 3
[2017-11-02 16:00:52,312|ReqReceiver.py:87][INFO] > length: 4
[2017-11-02 16:00:52,312|ReqReceiver.py:88][INFO] > encoding: 
[2017-11-02 16:00:52,312|ReqReceiver.py:89][INFO] > ===============================================
[2017-11-02 16:00:52,312|ClientService.py:34][INFO] > ===============================================
[2017-11-02 16:00:52,313|ClientService.py:35][INFO] > RESTIF -> [EXT]
[2017-11-02 16:00:52,313|ClientService.py:36][INFO] > ===============================================
[2017-11-02 16:00:52,313|ClientService.py:37][INFO] > URL : http://localhost:5555/departments/abc/123
[2017-11-02 16:00:52,313|ClientService.py:38][INFO] > HEADER : {'Content-type': 'application/json', 'Accept': 'application/json'}
[2017-11-02 16:00:52,313|ClientService.py:39][INFO] > TID : 200
[2017-11-02 16:00:52,313|ClientService.py:40][INFO] > BODY : {"name":"Hoyoung", "age": 123 }
[2017-11-02 16:00:52,314|ClientService.py:41][INFO] > ===============================================
[2017-11-02 16:00:52,337|ClientService.py:54][INFO] > ===============================================
[2017-11-02 16:00:52,337|ClientService.py:55][INFO] > [EXT] -> RESTIF
[2017-11-02 16:00:52,337|ClientService.py:56][INFO] > ===============================================
[2017-11-02 16:00:52,337|ClientService.py:57][INFO] > URL : http://localhost:5555/departments/abc/123
[2017-11-02 16:00:52,338|ClientService.py:58][INFO] > TID : 200
[2017-11-02 16:00:52,338|ClientService.py:59][INFO] > RESULT : 500
[2017-11-02 16:00:52,338|ClientService.py:60][INFO] > HEADER : {'date': 'Thu, 02 Nov 2017 07:00:52 GMT', 'content-length': '37', 'content-type': 'application/json', 'server': 'Werkzeug/0.12.2 Python/2.7.5'}
[2017-11-02 16:00:52,345|ClientService.py:61][INFO] > BODY : {"message": "Internal Server Error"}

[2017-11-02 16:00:52,345|ClientService.py:62][INFO] > ===============================================
[2017-11-02 16:00:52,346|PLTEConnector.py:89][ERROR] > sendMessage Error! 'PLTEConnector' object has no attribute 'plteQueue'
[2017-11-02 16:18:44,646|ReqReceiver.py:34][ERROR] > ReqReceiver Init
[2017-11-02 16:18:44,648|ResReceiver.py:33][INFO] > ResReceiver Init
[2017-11-02 16:18:44,649|PLTEConnector.py:28][DEBUG] > PLTEConnector Init
[2017-11-02 16:18:44,649|PLTEManager.py:22][DEBUG] > PLTE Manager Init
[2017-11-02 16:18:44,649|Connector.py:25][DEBUG] > Connector Init
[2017-11-02 16:18:56,922|ReqReceiver.py:73][INFO] > ===============================================
[2017-11-02 16:18:56,923|ReqReceiver.py:74][INFO] > [APP] -> RESTIF
[2017-11-02 16:18:56,923|ReqReceiver.py:75][INFO] > ===============================================
[2017-11-02 16:18:56,923|ReqReceiver.py:76][INFO] > msgType: 500
[2017-11-02 16:18:56,923|ReqReceiver.py:77][INFO] > tot_len : 100
[2017-11-02 16:18:56,923|ReqReceiver.py:78][INFO] > msgId : 200
[2017-11-02 16:18:56,923|ReqReceiver.py:79][INFO] > ehttp_idx : 300
[2017-11-02 16:18:56,923|ReqReceiver.py:80][INFO] > srcQid : 400
[2017-11-02 16:18:56,923|ReqReceiver.py:81][INFO] > srcSysId : 5
[2017-11-02 16:18:56,924|ReqReceiver.py:82][INFO] > jsonBody: {"name":"Hoyoung", "age": 123 }
[2017-11-02 16:18:56,924|ReqReceiver.py:83][INFO] > ===============================================
[2017-11-02 16:18:56,924|ReqReceiver.py:84][INFO] > method: 1
[2017-11-02 16:18:56,924|ReqReceiver.py:85][INFO] > api_type: 2
[2017-11-02 16:18:56,924|ReqReceiver.py:86][INFO] > op_type: 3
[2017-11-02 16:18:56,924|ReqReceiver.py:87][INFO] > length: 4
[2017-11-02 16:18:56,924|ReqReceiver.py:88][INFO] > encoding: 
[2017-11-02 16:18:56,924|ReqReceiver.py:89][INFO] > ===============================================
[2017-11-02 16:18:56,925|ClientService.py:34][INFO] > ===============================================
[2017-11-02 16:18:56,925|ClientService.py:35][INFO] > RESTIF -> [EXT]
[2017-11-02 16:18:56,925|ClientService.py:36][INFO] > ===============================================
[2017-11-02 16:18:56,925|ClientService.py:37][INFO] > URL : http://localhost:5555/departments/abc/123
[2017-11-02 16:18:56,925|ClientService.py:38][INFO] > HEADER : {'Content-type': 'application/json', 'Accept': 'application/json'}
[2017-11-02 16:18:56,925|ClientService.py:39][INFO] > TID : 200
[2017-11-02 16:18:56,925|ClientService.py:40][INFO] > BODY : {"name":"Hoyoung", "age": 123 }
[2017-11-02 16:18:56,926|ClientService.py:41][INFO] > ===============================================
[2017-11-02 16:18:56,951|ClientService.py:54][INFO] > ===============================================
[2017-11-02 16:18:56,952|ClientService.py:55][INFO] > [EXT] -> RESTIF
[2017-11-02 16:18:56,952|ClientService.py:56][INFO] > ===============================================
[2017-11-02 16:18:56,952|ClientService.py:57][INFO] > URL : http://localhost:5555/departments/abc/123
[2017-11-02 16:18:56,952|ClientService.py:58][INFO] > TID : 200
[2017-11-02 16:18:56,952|ClientService.py:59][INFO] > RESULT : 500
[2017-11-02 16:18:56,952|ClientService.py:60][INFO] > HEADER : {'date': 'Thu, 02 Nov 2017 07:18:56 GMT', 'content-length': '37', 'content-type': 'application/json', 'server': 'Werkzeug/0.12.2 Python/2.7.5'}
[2017-11-02 16:18:56,959|ClientService.py:61][INFO] > BODY : {"message": "Internal Server Error"}

[2017-11-02 16:18:56,959|ClientService.py:62][INFO] > ===============================================
[2017-11-02 16:18:56,959|ClientService.py:79][INFO] > ===============================================
[2017-11-02 16:18:56,959|ClientService.py:80][INFO] > TEST
[2017-11-02 16:18:56,960|ClientService.py:81][INFO] > ===============================================
[2017-11-02 16:18:56,960|ClientService.py:82][INFO] > tot_len : 1
[2017-11-02 16:18:56,960|ClientService.py:83][INFO] > msgId : 200
[2017-11-02 16:18:56,960|ClientService.py:84][INFO] > ehttp_idx : 1
[2017-11-02 16:18:56,960|ClientService.py:85][INFO] > srcQid : 1
[2017-11-02 16:18:56,960|ClientService.py:86][INFO] > srcSysId : 1
[2017-11-02 16:18:56,960|ClientService.py:87][INFO] > jsonBody: {"message": "Internal Server Error"}

[2017-11-02 16:18:56,960|ClientService.py:88][INFO] > ===============================================
[2017-11-02 16:18:56,960|ClientService.py:89][INFO] > method: 1
[2017-11-02 16:18:56,961|ClientService.py:90][INFO] > api_type: 2
[2017-11-02 16:18:56,961|ClientService.py:91][INFO] > op_type: 3
[2017-11-02 16:18:56,961|ClientService.py:92][INFO] > length: 4
[2017-11-02 16:18:56,961|ClientService.py:93][INFO] > encoding: 
[2017-11-02 16:18:56,961|ClientService.py:94][INFO] > ===============================================
[2017-11-02 16:18:56,961|PLTEConnector.py:93][INFO] > ===============================================
[2017-11-02 16:18:56,961|PLTEConnector.py:94][INFO] > RESTIF -> [APP]
[2017-11-02 16:18:56,962|PLTEConnector.py:95][INFO] > ===============================================
[2017-11-02 16:18:56,962|PLTEConnector.py:96][INFO] > API_NAME : http://localhost:5555/departments/abc/123
[2017-11-02 16:18:56,962|PLTEConnector.py:97][INFO] > PID   : 200
[2017-11-02 16:18:56,962|PLTEConnector.py:98][INFO] > RESTCODE : 500
[2017-11-02 16:18:56,962|PLTEConnector.py:99][INFO] > BODY   : {"message": "Internal Server Error"}

[2017-11-02 16:18:56,962|PLTEConnector.py:100][INFO] > ===============================================
[2017-11-02 16:19:53,404|ReqReceiver.py:73][INFO] > ===============================================
[2017-11-02 16:19:53,404|ReqReceiver.py:74][INFO] > [APP] -> RESTIF
[2017-11-02 16:19:53,404|ReqReceiver.py:75][INFO] > ===============================================
[2017-11-02 16:19:53,404|ReqReceiver.py:76][INFO] > msgType: 500
[2017-11-02 16:19:53,404|ReqReceiver.py:77][INFO] > tot_len : 100
[2017-11-02 16:19:53,404|ReqReceiver.py:78][INFO] > msgId : 200
[2017-11-02 16:19:53,404|ReqReceiver.py:79][INFO] > ehttp_idx : 300
[2017-11-02 16:19:53,404|ReqReceiver.py:80][INFO] > srcQid : 400
[2017-11-02 16:19:53,404|ReqReceiver.py:81][INFO] > srcSysId : 5
[2017-11-02 16:19:53,405|ReqReceiver.py:82][INFO] > jsonBody: {"name":"Hoyoung", "age": 123 }
[2017-11-02 16:19:53,405|ReqReceiver.py:83][INFO] > ===============================================
[2017-11-02 16:19:53,405|ReqReceiver.py:84][INFO] > method: 1
[2017-11-02 16:19:53,405|ReqReceiver.py:85][INFO] > api_type: 2
[2017-11-02 16:19:53,405|ReqReceiver.py:86][INFO] > op_type: 3
[2017-11-02 16:19:53,405|ReqReceiver.py:87][INFO] > length: 4
[2017-11-02 16:19:53,405|ReqReceiver.py:88][INFO] > encoding: 
[2017-11-02 16:19:53,405|ReqReceiver.py:89][INFO] > ===============================================
[2017-11-02 16:19:53,406|ClientService.py:34][INFO] > ===============================================
[2017-11-02 16:19:53,406|ClientService.py:35][INFO] > RESTIF -> [EXT]
[2017-11-02 16:19:53,406|ClientService.py:36][INFO] > ===============================================
[2017-11-02 16:19:53,406|ClientService.py:37][INFO] > URL : http://localhost:5555/departments/abc/123
[2017-11-02 16:19:53,406|ClientService.py:38][INFO] > HEADER : {'Content-type': 'application/json', 'Accept': 'application/json'}
[2017-11-02 16:19:53,406|ClientService.py:39][INFO] > TID : 200
[2017-11-02 16:19:53,407|ClientService.py:40][INFO] > BODY : {"name":"Hoyoung", "age": 123 }
[2017-11-02 16:19:53,407|ClientService.py:41][INFO] > ===============================================
[2017-11-02 16:19:53,412|ClientService.py:54][INFO] > ===============================================
[2017-11-02 16:19:53,413|ClientService.py:55][INFO] > [EXT] -> RESTIF
[2017-11-02 16:19:53,413|ClientService.py:56][INFO] > ===============================================
[2017-11-02 16:19:53,413|ClientService.py:57][INFO] > URL : http://localhost:5555/departments/abc/123
[2017-11-02 16:19:53,413|ClientService.py:58][INFO] > TID : 200
[2017-11-02 16:19:53,413|ClientService.py:59][INFO] > RESULT : 500
[2017-11-02 16:19:53,413|ClientService.py:60][INFO] > HEADER : {'date': 'Thu, 02 Nov 2017 07:19:53 GMT', 'content-length': '37', 'content-type': 'application/json', 'server': 'Werkzeug/0.12.2 Python/2.7.5'}
[2017-11-02 16:19:53,414|ClientService.py:61][INFO] > BODY : {"message": "Internal Server Error"}

[2017-11-02 16:19:53,414|ClientService.py:62][INFO] > ===============================================
[2017-11-02 16:19:53,414|ClientService.py:79][INFO] > ===============================================
[2017-11-02 16:19:53,414|ClientService.py:80][INFO] > TEST
[2017-11-02 16:19:53,414|ClientService.py:81][INFO] > ===============================================
[2017-11-02 16:19:53,414|ClientService.py:82][INFO] > tot_len : 1
[2017-11-02 16:19:53,414|ClientService.py:83][INFO] > msgId : 200
[2017-11-02 16:19:53,414|ClientService.py:84][INFO] > ehttp_idx : 1
[2017-11-02 16:19:53,415|ClientService.py:85][INFO] > srcQid : 1
[2017-11-02 16:19:53,415|ClientService.py:86][INFO] > srcSysId : 1
[2017-11-02 16:19:53,415|ClientService.py:87][INFO] > jsonBody: {"message": "Internal Server Error"}

[2017-11-02 16:19:53,415|ClientService.py:88][INFO] > ===============================================
[2017-11-02 16:19:53,415|ClientService.py:89][INFO] > method: 1
[2017-11-02 16:19:53,415|ClientService.py:90][INFO] > api_type: 2
[2017-11-02 16:19:53,415|ClientService.py:91][INFO] > op_type: 3
[2017-11-02 16:19:53,415|ClientService.py:92][INFO] > length: 4
[2017-11-02 16:19:53,415|ClientService.py:93][INFO] > encoding: 
[2017-11-02 16:19:53,416|ClientService.py:94][INFO] > ===============================================
[2017-11-02 16:19:53,416|PLTEConnector.py:93][INFO] > ===============================================
[2017-11-02 16:19:53,416|PLTEConnector.py:94][INFO] > RESTIF -> [APP]
[2017-11-02 16:19:53,416|PLTEConnector.py:95][INFO] > ===============================================
[2017-11-02 16:19:53,416|PLTEConnector.py:96][INFO] > API_NAME : http://localhost:5555/departments/abc/123
[2017-11-02 16:19:53,416|PLTEConnector.py:97][INFO] > PID   : 200
[2017-11-02 16:19:53,416|PLTEConnector.py:98][INFO] > RESTCODE : 500
[2017-11-02 16:19:53,416|PLTEConnector.py:99][INFO] > BODY   : {"message": "Internal Server Error"}

[2017-11-02 16:19:53,417|PLTEConnector.py:100][INFO] > ===============================================
[2017-11-02 16:20:20,951|ReqReceiver.py:34][ERROR] > ReqReceiver Init
[2017-11-02 16:20:20,953|ResReceiver.py:33][INFO] > ResReceiver Init
[2017-11-02 16:20:20,953|PLTEConnector.py:28][DEBUG] > PLTEConnector Init
[2017-11-02 16:20:20,953|PLTEManager.py:22][DEBUG] > PLTE Manager Init
[2017-11-02 16:20:20,953|Connector.py:25][DEBUG] > Connector Init
[2017-11-02 16:20:23,949|ReqReceiver.py:73][INFO] > ===============================================
[2017-11-02 16:20:23,949|ReqReceiver.py:74][INFO] > [APP] -> RESTIF
[2017-11-02 16:20:23,949|ReqReceiver.py:75][INFO] > ===============================================
[2017-11-02 16:20:23,949|ReqReceiver.py:76][INFO] > msgType: 500
[2017-11-02 16:20:23,949|ReqReceiver.py:77][INFO] > tot_len : 100
[2017-11-02 16:20:23,949|ReqReceiver.py:78][INFO] > msgId : 200
[2017-11-02 16:20:23,950|ReqReceiver.py:79][INFO] > ehttp_idx : 300
[2017-11-02 16:20:23,950|ReqReceiver.py:80][INFO] > srcQid : 400
[2017-11-02 16:20:23,950|ReqReceiver.py:81][INFO] > srcSysId : 5
[2017-11-02 16:20:23,950|ReqReceiver.py:82][INFO] > jsonBody: {"name":"Hoyoung", "age": 123 }
[2017-11-02 16:20:23,950|ReqReceiver.py:83][INFO] > ===============================================
[2017-11-02 16:20:23,950|ReqReceiver.py:84][INFO] > method: 1
[2017-11-02 16:20:23,950|ReqReceiver.py:85][INFO] > api_type: 2
[2017-11-02 16:20:23,950|ReqReceiver.py:86][INFO] > op_type: 3
[2017-11-02 16:20:23,950|ReqReceiver.py:87][INFO] > length: 4
[2017-11-02 16:20:23,950|ReqReceiver.py:88][INFO] > encoding: 
[2017-11-02 16:20:23,950|ReqReceiver.py:89][INFO] > ===============================================
[2017-11-02 16:20:23,951|ClientService.py:34][INFO] > ===============================================
[2017-11-02 16:20:23,951|ClientService.py:35][INFO] > RESTIF -> [EXT]
[2017-11-02 16:20:23,951|ClientService.py:36][INFO] > ===============================================
[2017-11-02 16:20:23,951|ClientService.py:37][INFO] > URL : http://localhost:5555/departments/abc/123
[2017-11-02 16:20:23,951|ClientService.py:38][INFO] > HEADER : {'Content-type': 'application/json', 'Accept': 'application/json'}
[2017-11-02 16:20:23,952|ClientService.py:39][INFO] > TID : 200
[2017-11-02 16:20:23,952|ClientService.py:40][INFO] > BODY : {"name":"Hoyoung", "age": 123 }
[2017-11-02 16:20:23,952|ClientService.py:41][INFO] > ===============================================
[2017-11-02 16:20:23,976|ClientService.py:54][INFO] > ===============================================
[2017-11-02 16:20:23,976|ClientService.py:55][INFO] > [EXT] -> RESTIF
[2017-11-02 16:20:23,977|ClientService.py:56][INFO] > ===============================================
[2017-11-02 16:20:23,977|ClientService.py:57][INFO] > URL : http://localhost:5555/departments/abc/123
[2017-11-02 16:20:23,977|ClientService.py:58][INFO] > TID : 200
[2017-11-02 16:20:23,977|ClientService.py:59][INFO] > RESULT : 500
[2017-11-02 16:20:23,977|ClientService.py:60][INFO] > HEADER : {'date': 'Thu, 02 Nov 2017 07:20:23 GMT', 'content-length': '37', 'content-type': 'application/json', 'server': 'Werkzeug/0.12.2 Python/2.7.5'}
[2017-11-02 16:20:23,984|ClientService.py:61][INFO] > BODY : {"message": "Internal Server Error"}

[2017-11-02 16:20:23,984|ClientService.py:62][INFO] > ===============================================
[2017-11-02 16:20:23,984|PLTEConnector.py:93][INFO] > ===============================================
[2017-11-02 16:20:23,984|PLTEConnector.py:94][INFO] > RESTIF -> [APP]
[2017-11-02 16:20:23,985|PLTEConnector.py:95][INFO] > ===============================================
[2017-11-02 16:20:23,985|PLTEConnector.py:96][INFO] > API_NAME : http://localhost:5555/departments/abc/123
[2017-11-02 16:20:23,985|PLTEConnector.py:97][INFO] > PID   : 200
[2017-11-02 16:20:23,985|PLTEConnector.py:98][INFO] > RESTCODE : 500
[2017-11-02 16:20:23,985|PLTEConnector.py:99][INFO] > BODY   : {"message": "Internal Server Error"}

[2017-11-02 16:20:23,985|PLTEConnector.py:100][INFO] > ===============================================
[2017-11-02 16:21:29,161|ReqReceiver.py:34][ERROR] > ReqReceiver Init
[2017-11-02 16:21:29,162|ResReceiver.py:33][INFO] > ResReceiver Init
[2017-11-02 16:21:29,162|PLTEConnector.py:28][DEBUG] > PLTEConnector Init
[2017-11-02 16:21:29,162|PLTEManager.py:22][DEBUG] > PLTE Manager Init
[2017-11-02 16:21:29,162|Connector.py:25][DEBUG] > Connector Init
[2017-11-02 16:21:29,162|PLTEConnector.py:35][ERROR] > msgQueue Connection Failed.. PLTE QUEUE_ID[12345]
[2017-11-02 16:21:30,263|ReqReceiver.py:73][INFO] > ===============================================
[2017-11-02 16:21:30,263|ReqReceiver.py:74][INFO] > [APP] -> RESTIF
[2017-11-02 16:21:30,263|ReqReceiver.py:75][INFO] > ===============================================
[2017-11-02 16:21:30,263|ReqReceiver.py:76][INFO] > msgType: 500
[2017-11-02 16:21:30,263|ReqReceiver.py:77][INFO] > tot_len : 100
[2017-11-02 16:21:30,263|ReqReceiver.py:78][INFO] > msgId : 200
[2017-11-02 16:21:30,263|ReqReceiver.py:79][INFO] > ehttp_idx : 300
[2017-11-02 16:21:30,263|ReqReceiver.py:80][INFO] > srcQid : 400
[2017-11-02 16:21:30,263|ReqReceiver.py:81][INFO] > srcSysId : 5
[2017-11-02 16:21:30,264|ReqReceiver.py:82][INFO] > jsonBody: {"name":"Hoyoung", "age": 123 }
[2017-11-02 16:21:30,264|ReqReceiver.py:83][INFO] > ===============================================
[2017-11-02 16:21:30,264|ReqReceiver.py:84][INFO] > method: 1
[2017-11-02 16:21:30,264|ReqReceiver.py:85][INFO] > api_type: 2
[2017-11-02 16:21:30,264|ReqReceiver.py:86][INFO] > op_type: 3
[2017-11-02 16:21:30,264|ReqReceiver.py:87][INFO] > length: 4
[2017-11-02 16:21:30,264|ReqReceiver.py:88][INFO] > encoding: 5
[2017-11-02 16:21:30,264|ReqReceiver.py:89][INFO] > ===============================================
[2017-11-02 16:21:30,265|ClientService.py:34][INFO] > ===============================================
[2017-11-02 16:21:30,265|ClientService.py:35][INFO] > RESTIF -> [EXT]
[2017-11-02 16:21:30,265|ClientService.py:36][INFO] > ===============================================
[2017-11-02 16:21:30,265|ClientService.py:37][INFO] > URL : http://localhost:5555/departments/abc/123
[2017-11-02 16:21:30,265|ClientService.py:38][INFO] > HEADER : {'Content-type': 'application/json', 'Accept': 'application/json'}
[2017-11-02 16:21:30,265|ClientService.py:39][INFO] > TID : 200
[2017-11-02 16:21:30,265|ClientService.py:40][INFO] > BODY : {"name":"Hoyoung", "age": 123 }
[2017-11-02 16:21:30,266|ClientService.py:41][INFO] > ===============================================
[2017-11-02 16:21:30,288|ClientService.py:54][INFO] > ===============================================
[2017-11-02 16:21:30,288|ClientService.py:55][INFO] > [EXT] -> RESTIF
[2017-11-02 16:21:30,288|ClientService.py:56][INFO] > ===============================================
[2017-11-02 16:21:30,288|ClientService.py:57][INFO] > URL : http://localhost:5555/departments/abc/123
[2017-11-02 16:21:30,288|ClientService.py:58][INFO] > TID : 200
[2017-11-02 16:21:30,288|ClientService.py:59][INFO] > RESULT : 500
[2017-11-02 16:21:30,288|ClientService.py:60][INFO] > HEADER : {'date': 'Thu, 02 Nov 2017 07:21:30 GMT', 'content-length': '37', 'content-type': 'application/json', 'server': 'Werkzeug/0.12.2 Python/2.7.5'}
[2017-11-02 16:21:30,295|ClientService.py:61][INFO] > BODY : {"message": "Internal Server Error"}

[2017-11-02 16:21:30,295|ClientService.py:62][INFO] > ===============================================
[2017-11-02 16:21:30,295|PLTEConnector.py:89][ERROR] > sendMessage Error! 'PLTEConnector' object has no attribute 'plteQueue'
[2017-11-02 16:21:36,175|ReqReceiver.py:73][INFO] > ===============================================
[2017-11-02 16:21:36,175|ReqReceiver.py:74][INFO] > [APP] -> RESTIF
[2017-11-02 16:21:36,175|ReqReceiver.py:75][INFO] > ===============================================
[2017-11-02 16:21:36,176|ReqReceiver.py:76][INFO] > msgType: 500
[2017-11-02 16:21:36,176|ReqReceiver.py:77][INFO] > tot_len : 100
[2017-11-02 16:21:36,176|ReqReceiver.py:78][INFO] > msgId : 200
[2017-11-02 16:21:36,176|ReqReceiver.py:79][INFO] > ehttp_idx : 300
[2017-11-02 16:21:36,176|ReqReceiver.py:80][INFO] > srcQid : 400
[2017-11-02 16:21:36,176|ReqReceiver.py:81][INFO] > srcSysId : 5
[2017-11-02 16:21:36,176|ReqReceiver.py:82][INFO] > jsonBody: {"name":"Hoyoung", "age": 123 }
[2017-11-02 16:21:36,176|ReqReceiver.py:83][INFO] > ===============================================
[2017-11-02 16:21:36,176|ReqReceiver.py:84][INFO] > method: 1
[2017-11-02 16:21:36,176|ReqReceiver.py:85][INFO] > api_type: 2
[2017-11-02 16:21:36,177|ReqReceiver.py:86][INFO] > op_type: 3
[2017-11-02 16:21:36,177|ReqReceiver.py:87][INFO] > length: 4
[2017-11-02 16:21:36,177|ReqReceiver.py:88][INFO] > encoding: 5
[2017-11-02 16:21:36,177|ReqReceiver.py:89][INFO] > ===============================================
[2017-11-02 16:21:36,177|ClientService.py:34][INFO] > ===============================================
[2017-11-02 16:21:36,177|ClientService.py:35][INFO] > RESTIF -> [EXT]
[2017-11-02 16:21:36,178|ClientService.py:36][INFO] > ===============================================
[2017-11-02 16:21:36,178|ClientService.py:37][INFO] > URL : http://localhost:5555/departments/abc/123
[2017-11-02 16:21:36,178|ClientService.py:38][INFO] > HEADER : {'Content-type': 'application/json', 'Accept': 'application/json'}
[2017-11-02 16:21:36,178|ClientService.py:39][INFO] > TID : 200
[2017-11-02 16:21:36,178|ClientService.py:40][INFO] > BODY : {"name":"Hoyoung", "age": 123 }
[2017-11-02 16:21:36,178|ClientService.py:41][INFO] > ===============================================
[2017-11-02 16:21:36,183|ClientService.py:54][INFO] > ===============================================
[2017-11-02 16:21:36,184|ClientService.py:55][INFO] > [EXT] -> RESTIF
[2017-11-02 16:21:36,184|ClientService.py:56][INFO] > ===============================================
[2017-11-02 16:21:36,184|ClientService.py:57][INFO] > URL : http://localhost:5555/departments/abc/123
[2017-11-02 16:21:36,184|ClientService.py:58][INFO] > TID : 200
[2017-11-02 16:21:36,184|ClientService.py:59][INFO] > RESULT : 500
[2017-11-02 16:21:36,184|ClientService.py:60][INFO] > HEADER : {'date': 'Thu, 02 Nov 2017 07:21:36 GMT', 'content-length': '37', 'content-type': 'application/json', 'server': 'Werkzeug/0.12.2 Python/2.7.5'}
[2017-11-02 16:21:36,184|ClientService.py:61][INFO] > BODY : {"message": "Internal Server Error"}

[2017-11-02 16:21:36,185|ClientService.py:62][INFO] > ===============================================
[2017-11-02 16:21:36,185|PLTEConnector.py:89][ERROR] > sendMessage Error! 'PLTEConnector' object has no attribute 'plteQueue'
[2017-11-02 16:21:49,245|ReqReceiver.py:73][INFO] > ===============================================
[2017-11-02 16:21:49,246|ReqReceiver.py:74][INFO] > [APP] -> RESTIF
[2017-11-02 16:21:49,246|ReqReceiver.py:75][INFO] > ===============================================
[2017-11-02 16:21:49,246|ReqReceiver.py:76][INFO] > msgType: 500
[2017-11-02 16:21:49,246|ReqReceiver.py:77][INFO] > tot_len : 100
[2017-11-02 16:21:49,246|ReqReceiver.py:78][INFO] > msgId : 200
[2017-11-02 16:21:49,246|ReqReceiver.py:79][INFO] > ehttp_idx : 300
[2017-11-02 16:21:49,246|ReqReceiver.py:80][INFO] > srcQid : 400
[2017-11-02 16:21:49,246|ReqReceiver.py:81][INFO] > srcSysId : 5
[2017-11-02 16:21:49,246|ReqReceiver.py:82][INFO] > jsonBody: {"name":"Hoyoung", "age": 123 }
[2017-11-02 16:21:49,247|ReqReceiver.py:83][INFO] > ===============================================
[2017-11-02 16:21:49,247|ReqReceiver.py:84][INFO] > method: 1
[2017-11-02 16:21:49,247|ReqReceiver.py:85][INFO] > api_type: 2
[2017-11-02 16:21:49,247|ReqReceiver.py:86][INFO] > op_type: 3
[2017-11-02 16:21:49,247|ReqReceiver.py:87][INFO] > length: 4
[2017-11-02 16:21:49,247|ReqReceiver.py:88][INFO] > encoding: 5
[2017-11-02 16:21:49,247|ReqReceiver.py:89][INFO] > ===============================================
[2017-11-02 16:21:49,247|ClientService.py:34][INFO] > ===============================================
[2017-11-02 16:21:49,248|ClientService.py:35][INFO] > RESTIF -> [EXT]
[2017-11-02 16:21:49,248|ClientService.py:36][INFO] > ===============================================
[2017-11-02 16:21:49,248|ClientService.py:37][INFO] > URL : http://localhost:5555/departments/abc/123
[2017-11-02 16:21:49,248|ClientService.py:38][INFO] > HEADER : {'Content-type': 'application/json', 'Accept': 'application/json'}
[2017-11-02 16:21:49,248|ClientService.py:39][INFO] > TID : 200
[2017-11-02 16:21:49,248|ClientService.py:40][INFO] > BODY : {"name":"Hoyoung", "age": 123 }
[2017-11-02 16:21:49,248|ClientService.py:41][INFO] > ===============================================
[2017-11-02 16:21:49,252|ClientService.py:54][INFO] > ===============================================
[2017-11-02 16:21:49,252|ClientService.py:55][INFO] > [EXT] -> RESTIF
[2017-11-02 16:21:49,253|ClientService.py:56][INFO] > ===============================================
[2017-11-02 16:21:49,253|ClientService.py:57][INFO] > URL : http://localhost:5555/departments/abc/123
[2017-11-02 16:21:49,253|ClientService.py:58][INFO] > TID : 200
[2017-11-02 16:21:49,253|ClientService.py:59][INFO] > RESULT : 500
[2017-11-02 16:21:49,253|ClientService.py:60][INFO] > HEADER : {'date': 'Thu, 02 Nov 2017 07:21:49 GMT', 'content-length': '37', 'content-type': 'application/json', 'server': 'Werkzeug/0.12.2 Python/2.7.5'}
[2017-11-02 16:21:49,253|ClientService.py:61][INFO] > BODY : {"message": "Internal Server Error"}

[2017-11-02 16:21:49,253|ClientService.py:62][INFO] > ===============================================
[2017-11-02 16:21:49,253|PLTEConnector.py:89][ERROR] > sendMessage Error! 'PLTEConnector' object has no attribute 'plteQueue'
[2017-11-02 16:22:11,930|ReqReceiver.py:34][ERROR] > ReqReceiver Init
[2017-11-02 16:22:11,930|ResReceiver.py:33][INFO] > ResReceiver Init
[2017-11-02 16:22:11,931|PLTEConnector.py:28][DEBUG] > PLTEConnector Init
[2017-11-02 16:22:11,931|PLTEManager.py:22][DEBUG] > PLTE Manager Init
[2017-11-02 16:22:11,931|Connector.py:25][DEBUG] > Connector Init
[2017-11-02 16:22:11,931|PLTEConnector.py:35][ERROR] > msgQueue Connection Failed.. PLTE QUEUE_ID[12345]
[2017-11-02 16:22:19,300|ReqReceiver.py:34][ERROR] > ReqReceiver Init
[2017-11-02 16:22:19,301|ResReceiver.py:33][INFO] > ResReceiver Init
[2017-11-02 16:22:19,301|PLTEConnector.py:28][DEBUG] > PLTEConnector Init
[2017-11-02 16:22:19,301|PLTEManager.py:22][DEBUG] > PLTE Manager Init
[2017-11-02 16:22:19,301|Connector.py:25][DEBUG] > Connector Init
[2017-11-02 16:22:19,301|PLTEConnector.py:35][ERROR] > msgQueue Connection Failed.. PLTE QUEUE_ID[12345]
[2017-11-02 16:22:22,033|ReqReceiver.py:73][INFO] > ===============================================
[2017-11-02 16:22:22,033|ReqReceiver.py:74][INFO] > [APP] -> RESTIF
[2017-11-02 16:22:22,034|ReqReceiver.py:75][INFO] > ===============================================
[2017-11-02 16:22:22,034|ReqReceiver.py:76][INFO] > msgType: 500
[2017-11-02 16:22:22,034|ReqReceiver.py:77][INFO] > tot_len : 100
[2017-11-02 16:22:22,034|ReqReceiver.py:78][INFO] > msgId : 200
[2017-11-02 16:22:22,034|ReqReceiver.py:79][INFO] > ehttp_idx : 300
[2017-11-02 16:22:22,034|ReqReceiver.py:80][INFO] > srcQid : 400
[2017-11-02 16:22:22,034|ReqReceiver.py:81][INFO] > srcSysId : 5
[2017-11-02 16:22:22,034|ReqReceiver.py:82][INFO] > jsonBody: {"name":"Hoyoung", "age": 123 }
[2017-11-02 16:22:22,034|ReqReceiver.py:83][INFO] > ===============================================
[2017-11-02 16:22:22,034|ReqReceiver.py:84][INFO] > method: 1
[2017-11-02 16:22:22,034|ReqReceiver.py:85][INFO] > api_type: 2
[2017-11-02 16:22:22,035|ReqReceiver.py:86][INFO] > op_type: 3
[2017-11-02 16:22:22,035|ReqReceiver.py:87][INFO] > length: 4
[2017-11-02 16:22:22,035|ReqReceiver.py:88][INFO] > encoding: 5
[2017-11-02 16:22:22,035|ReqReceiver.py:89][INFO] > ===============================================
[2017-11-02 16:22:22,035|ClientService.py:34][INFO] > ===============================================
[2017-11-02 16:22:22,036|ClientService.py:35][INFO] > RESTIF -> [EXT]
[2017-11-02 16:22:22,036|ClientService.py:36][INFO] > ===============================================
[2017-11-02 16:22:22,036|ClientService.py:37][INFO] > URL : http://localhost:5555/departments/abc/123
[2017-11-02 16:22:22,036|ClientService.py:38][INFO] > HEADER : {'Content-type': 'application/json', 'Accept': 'application/json'}
[2017-11-02 16:22:22,036|ClientService.py:39][INFO] > TID : 200
[2017-11-02 16:22:22,036|ClientService.py:40][INFO] > BODY : {"name":"Hoyoung", "age": 123 }
[2017-11-02 16:22:22,036|ClientService.py:41][INFO] > ===============================================
[2017-11-02 16:22:22,059|ClientService.py:54][INFO] > ===============================================
[2017-11-02 16:22:22,059|ClientService.py:55][INFO] > [EXT] -> RESTIF
[2017-11-02 16:22:22,059|ClientService.py:56][INFO] > ===============================================
[2017-11-02 16:22:22,059|ClientService.py:57][INFO] > URL : http://localhost:5555/departments/abc/123
[2017-11-02 16:22:22,060|ClientService.py:58][INFO] > TID : 200
[2017-11-02 16:22:22,060|ClientService.py:59][INFO] > RESULT : 500
[2017-11-02 16:22:22,060|ClientService.py:60][INFO] > HEADER : {'date': 'Thu, 02 Nov 2017 07:22:22 GMT', 'content-length': '37', 'content-type': 'application/json', 'server': 'Werkzeug/0.12.2 Python/2.7.5'}
[2017-11-02 16:22:22,066|ClientService.py:61][INFO] > BODY : {"message": "Internal Server Error"}

[2017-11-02 16:22:22,066|ClientService.py:62][INFO] > ===============================================
[2017-11-02 16:22:22,067|ClientService.py:79][INFO] > ===============================================
[2017-11-02 16:22:22,067|ClientService.py:80][INFO] > TEST
[2017-11-02 16:22:22,067|ClientService.py:81][INFO] > ===============================================
[2017-11-02 16:22:22,067|ClientService.py:82][INFO] > tot_len : 1
[2017-11-02 16:22:22,067|ClientService.py:83][INFO] > msgId : 200
[2017-11-02 16:22:22,067|ClientService.py:84][INFO] > ehttp_idx : 1
[2017-11-02 16:22:22,067|ClientService.py:85][INFO] > srcQid : 1
[2017-11-02 16:22:22,067|ClientService.py:86][INFO] > srcSysId : 1
[2017-11-02 16:22:22,068|ClientService.py:87][INFO] > jsonBody: {"message": "Internal Server Error"}

[2017-11-02 16:22:22,068|ClientService.py:88][INFO] > ===============================================
[2017-11-02 16:22:22,068|ClientService.py:89][INFO] > method: 1
[2017-11-02 16:22:22,068|ClientService.py:90][INFO] > api_type: 2
[2017-11-02 16:22:22,068|ClientService.py:91][INFO] > op_type: 3
[2017-11-02 16:22:22,068|ClientService.py:92][INFO] > length: 4
[2017-11-02 16:22:22,068|ClientService.py:93][INFO] > encoding: 5
[2017-11-02 16:22:22,068|ClientService.py:94][INFO] > ===============================================
[2017-11-02 16:22:22,068|PLTEConnector.py:89][ERROR] > sendMessage Error! 'PLTEConnector' object has no attribute 'plteQueue'
[2017-11-02 16:25:10,848|ReqReceiver.py:34][ERROR] > ReqReceiver Init
[2017-11-02 16:25:10,849|ResReceiver.py:33][INFO] > ResReceiver Init
[2017-11-02 16:25:10,850|PLTEConnector.py:28][DEBUG] > PLTEConnector Init
[2017-11-02 16:25:10,850|PLTEManager.py:22][DEBUG] > PLTE Manager Init
[2017-11-02 16:25:10,850|Connector.py:25][DEBUG] > Connector Init
[2017-11-02 16:25:25,535|ReqReceiver.py:73][INFO] > ===============================================
[2017-11-02 16:25:25,535|ReqReceiver.py:74][INFO] > [APP] -> RESTIF
[2017-11-02 16:25:25,536|ReqReceiver.py:75][INFO] > ===============================================
[2017-11-02 16:25:25,536|ReqReceiver.py:76][INFO] > msgType: 500
[2017-11-02 16:25:25,536|ReqReceiver.py:77][INFO] > tot_len : 100
[2017-11-02 16:25:25,536|ReqReceiver.py:78][INFO] > msgId : 200
[2017-11-02 16:25:25,536|ReqReceiver.py:79][INFO] > ehttp_idx : 300
[2017-11-02 16:25:25,536|ReqReceiver.py:80][INFO] > srcQid : 400
[2017-11-02 16:25:25,536|ReqReceiver.py:81][INFO] > srcSysId : 5
[2017-11-02 16:25:25,536|ReqReceiver.py:82][INFO] > jsonBody: {"name":"Hoyoung", "age": 123 }
[2017-11-02 16:25:25,536|ReqReceiver.py:83][INFO] > ===============================================
[2017-11-02 16:25:25,536|ReqReceiver.py:84][INFO] > method: 1
[2017-11-02 16:25:25,536|ReqReceiver.py:85][INFO] > api_type: 2
[2017-11-02 16:25:25,537|ReqReceiver.py:86][INFO] > op_type: 3
[2017-11-02 16:25:25,537|ReqReceiver.py:87][INFO] > length: 4
[2017-11-02 16:25:25,537|ReqReceiver.py:88][INFO] > encoding: 5
[2017-11-02 16:25:25,537|ReqReceiver.py:89][INFO] > ===============================================
[2017-11-02 16:25:25,537|ClientService.py:35][INFO] > ===============================================
[2017-11-02 16:25:25,537|ClientService.py:36][INFO] > RESTIF -> [EXT]
[2017-11-02 16:25:25,538|ClientService.py:37][INFO] > ===============================================
[2017-11-02 16:25:25,538|ClientService.py:38][INFO] > URL : http://localhost:5555/departments/abc/123
[2017-11-02 16:25:25,538|ClientService.py:39][INFO] > HEADER : {'Content-type': 'application/x-www-form-urlencoded', 'Accept': 'application/json'}
[2017-11-02 16:25:25,538|ClientService.py:40][INFO] > TID : 200
[2017-11-02 16:25:25,538|ClientService.py:41][INFO] > BODY : {"name":"Hoyoung", "age": 123 }
[2017-11-02 16:25:25,538|ClientService.py:42][INFO] > ===============================================
[2017-11-02 16:25:25,563|ClientService.py:55][INFO] > ===============================================
[2017-11-02 16:25:25,563|ClientService.py:56][INFO] > [EXT] -> RESTIF
[2017-11-02 16:25:25,564|ClientService.py:57][INFO] > ===============================================
[2017-11-02 16:25:25,564|ClientService.py:58][INFO] > URL : http://localhost:5555/departments/abc/123
[2017-11-02 16:25:25,564|ClientService.py:59][INFO] > TID : 200
[2017-11-02 16:25:25,564|ClientService.py:60][INFO] > RESULT : 500
[2017-11-02 16:25:25,564|ClientService.py:61][INFO] > HEADER : {'date': 'Thu, 02 Nov 2017 07:25:25 GMT', 'content-length': '37', 'content-type': 'application/json', 'server': 'Werkzeug/0.12.2 Python/2.7.5'}
[2017-11-02 16:25:25,570|ClientService.py:62][INFO] > BODY : {"message": "Internal Server Error"}

[2017-11-02 16:25:25,570|ClientService.py:63][INFO] > ===============================================
[2017-11-02 16:25:25,571|ClientService.py:80][INFO] > ===============================================
[2017-11-02 16:25:25,571|ClientService.py:81][INFO] > TEST
[2017-11-02 16:25:25,571|ClientService.py:82][INFO] > ===============================================
[2017-11-02 16:25:25,571|ClientService.py:83][INFO] > tot_len : 1
[2017-11-02 16:25:25,571|ClientService.py:84][INFO] > msgId : 200
[2017-11-02 16:25:25,571|ClientService.py:85][INFO] > ehttp_idx : 1
[2017-11-02 16:25:25,571|ClientService.py:86][INFO] > srcQid : 1
[2017-11-02 16:25:25,571|ClientService.py:87][INFO] > srcSysId : 1
[2017-11-02 16:25:25,571|ClientService.py:88][INFO] > jsonBody: {"message": "Internal Server Error"}

[2017-11-02 16:25:25,571|ClientService.py:89][INFO] > ===============================================
[2017-11-02 16:25:25,572|ClientService.py:90][INFO] > method: 1
[2017-11-02 16:25:25,572|ClientService.py:91][INFO] > api_type: 2
[2017-11-02 16:25:25,572|ClientService.py:92][INFO] > op_type: 3
[2017-11-02 16:25:25,572|ClientService.py:93][INFO] > length: 4
[2017-11-02 16:25:25,572|ClientService.py:94][INFO] > encoding: 5
[2017-11-02 16:25:25,572|ClientService.py:95][INFO] > ===============================================
[2017-11-02 16:25:25,573|PLTEConnector.py:93][INFO] > ===============================================
[2017-11-02 16:25:25,573|PLTEConnector.py:94][INFO] > RESTIF -> [APP]
[2017-11-02 16:25:25,573|PLTEConnector.py:95][INFO] > ===============================================
[2017-11-02 16:25:25,573|PLTEConnector.py:96][INFO] > API_NAME : http://localhost:5555/departments/abc/123
[2017-11-02 16:25:25,573|PLTEConnector.py:97][INFO] > PID   : 200
[2017-11-02 16:25:25,574|PLTEConnector.py:98][INFO] > RESTCODE : 500
[2017-11-02 16:25:25,574|PLTEConnector.py:99][INFO] > BODY   : {"message": "Internal Server Error"}

[2017-11-02 16:25:25,574|PLTEConnector.py:100][INFO] > ===============================================
